query launchList {
    launchesPast(limit: 10) {
        id
        mission_name
        launch_date_local
        launch_site {
            site_name_long
            site_name
        }
        links {
            article_link
            video_link
            mission_patch
        }
        rocket {
            rocket_name
        }
    }
}